import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {Button, ButtonGoogle, ButtonTwo, ButtonApple} from '@/components/Button'
import Footer from '/components/Footer'
import { GoogleLogo, Xlogo, AppleLogo } from '@/components/Image'
import { HeaderOne, HeaderTwo, HeaderThree } from '@/components/Headers'
import { OrText, CookiesText } from '@/components/Paragraph'
import { OrLine } from '@/components/OrLine'


export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
    <div className={`${styles.MainContainer}`}>
    <div className={`${styles.XlogoContainer}`}>
      <Xlogo/>
    </div>
    <div className={`${styles.AccountContainer}`}>
    <div className='Headers'>
      <HeaderOne/>
      <HeaderTwo/>
    </div>
    <div className='Buttons'>
    <div className={`${styles.GoogleAppleContainer}`}>
    <ButtonGoogle/>
    <ButtonApple/>
    </div>
    <div className={`${styles.ORlineContainer}`}>
      <OrLine/><OrText/><OrLine/>
    </div>
    <div className={`${styles.CreateContainer}`}>
    <Button/>
  <CookiesText/>
<div className={`${styles.Login}`}>
    <HeaderThree/>
  <ButtonTwo/>
</div>
</div>
</div>
</div> 
</div>
<div className={`${styles.FooterContainer}`}>
<Footer/>
</div>
      </main>
    </>
  )
}
