import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {Button, ButtonGoogle, ButtonTwo, ButtonApple} from '@/components/Button'
import Footer from '/components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
    <div className='MainContainer'>
    <div className='XlogoContainer'>
      <img class='Xlogo' src='/X_logo_2023_original.svg'></img>
    </div>
    <div className='AccountContainer'>
    <div className='Headers'>
    <h1>Happening now</h1>
    <h2>Join Today.</h2>
    </div>
    <div className='Buttons'>
    <div className='GoogleAppleContainer'>
    <ButtonGoogle/>
    <ButtonApple/>
    <div className='ORlineContainer'>
      <hr></hr> <p class='orText'>or</p> <hr></hr>
    </div>
    </div>
    <div className='CreateContainer'>
    <Button/>
  <p className='Cookies'>By signing up, you agree to the <span className='Bluetext'>Terms of Service</span> and <span className='Bluetext'>Privacy Policy,</span> including <span className='Bluetext'>Cookie Use.</span></p>
<div className='Login'>
<h3>Already have an account?</h3>
<ButtonTwo/>
</div>
</div>
</div>
</div> 
</div>
<Footer/>
      </main>
    </>
  )
}
